import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
        <header>
    <h1>ポートフォリオサイト</h1>
    <nav>
      <a href="#about">自己紹介</a>
      <a href="#works">作品集</a>
      <a href="#contact">お問い合わせ</a>
    </nav>
  </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
